### PR TITLE
Update Python API to 3.1.0.2

### PR DESCRIPTION
**Pull request by mmeldo**
Implement list of API changes: https://gist.github.com/brine/cd5d674a06c98ead1404

### CODE REVIEW

**Comment by db0** [comment]
OOf this seems massive. I hope you've done extensive testing?

**Comment by mmeldo** [comment]
Only seems. The biggest changes are to the events, which I tested all and the askCard function which was replaced. But that got me thinking I did not have tested ingame the new dialog, just via dev console. So yeah, the return value needs to be corrected.

**Comment by mmeldo** [comment]
Ok, found 2 bugs that needed fixing. And even though I did not do that extensive testing, I tested again all events Doomtown uses, some dudes using the new card dialog (all of them are not needed as the method call is the same), and even some of the properties even though only change there way they are accessed. If you see something else that should be tested let me know.

**Comment by mmeldo** [comment]
For the peace of my mind, I went through all the Python API changes again and marked the changes in the list:

Tested events again, but since the only change there is a way arguments are passed, and they were called properly when tested in game I believe nothing else needs to be tested.

###PYTHON CHANGES
- askCard() - Removed split-functionality when a list is passed instead of a dictionary, now behaves old-school (see cardDlg)
  - created new function askCardFromList that takes the same arguments and returns same return type.
  - tested in game on various dudes using this function
- isTableBackgroundFlipped() - RENAMED, moved to Table class (see table.invertBackground)
  - not used
- setTableBackgroundFlipped() - RENAMED, moved to Table class (see table.invertBackground)
  - not used
- group.setController() - RENAMED (see card.controller)
  - not used
- card.switchTo() - RENAMED (see card.alternate)
  - not used
- card.setController() - RENAMED (see card.controller)
  - simple rename, tested in game and in dev console
- card.height() - RENAMED (see card.height)
  - not used
- card.width() - RENAMED (see card.width)
  - not used
- card.size() - RENAMED (see card.size)
  - not used
- card.setIndex() - RENAMED (see card.index)
  - simple rename, used only with orgAttachments, tested in game
- card.getIndex() - RENAMED(see card.index)
  - not used
- player.isActivePlayer - RENAMED (see player.isActive)
  - not used
- player.setActivePlayer() - RENAMED (see player.setActive() )
  - not used
- player.hasInvertedTable() - RENAMED (see player.isInverted)
  - not used
- table.offset() - Moved to Card class (see card.offset() )
  - not used
- table.isInverted() - Moved to Card class (see card.isInverted() )
  - not used
- table.setBoardImage() - MODIFIED FUNCTIONALITY (see table.board)
  - not used

**Comment by db0** [comment]
OK, I'm not really involved atm so I will not test it myself. If it breaks, I'll redirect the flames to you :P

**Pull request merged**
