### PR TITLE
Fixed misspelling of Whiskey Flask in core set definition.

### PR DESCRIPTION
**Pull request by jrmitch120**

### CODE REVIEW

**Comment by db0** [comment]
I think I had that fixed shortly before you told me :)

**Comment by jrmitch120** [comment]
It's still there ;)

https://github.com/db0/Doomtown-Reloaded-OCTGN/blob/master/o8g/Sets/Core%20Set/set.xml#L2423

I'm just trying to clean up some stuff, so no worries.  I think I ran across it while trying to familiarize myself with the o8g format.

**Comment by db0** [comment]
Oh damn. In that case I must have missed that, so thanks for reminding me :)

**Comment by db0** [comment]
Where have you been btw? Haven't seen you around much

**Comment by jrmitch120** [comment]
Been pretty well thanks!  Spending most of my free time lately trying to "tech up" on some new programming stuff.  I need to get back to some Doomtown, love that game.  Even though I suck at it something fierce.

**Comment by db0** [comment]
Haha, come online and we'll play sometime :) You stopped working on challengeboards?

**Comment by jrmitch120** [comment]
I should get back to it, but I have let it go for some time.  I have side project ADD.

**Pull request merged**
