### PR TITLE
Changing minimum OCTGN required version, and upping the game version.…

### PR DESCRIPTION
**Pull request by J0eJames**
This is a shot in the dark to figure out why octgn isn't seeing a new package version...

The last time this happened to me, it just took uploading a new package with a new version and then it worked.  That makes no sense, but not sure what else to try.

### CODE REVIEW

**Comment by J0eJames** [comment]
Another quick note - the minimum octgn version I changed it to is exactly what I'm using in the PT doomtown version, which has been working fine the past several weeks.

**Comment by db0** [comment]
Nevermind my previous comment. I was using the wrong octgn. Uploaded now. See if it works.

**Comment by J0eJames** [comment]
It worked!  Thanks @db0 !!!
(also, very frustrating to work with octgn these days, but I'm getting plenty of practice getting around their weird bugs with the PT version...)

**Comment by db0** [comment]
hah, it has always been difficult to work with OCTGN. I had epic fights when the developers kept changing their APIs without notice etc.

**Pull request merged**
